name: Deployment Frontend (DEV)
on:
  workflow_dispatch:
    inputs:
      DEPLOY_APP_CUSTOMERS:
              type: boolean
              description: "(Customers) Enable customer app deployment"
              default: true
  schedule:
    # Run once a day. 7PM UTC.
    - cron: "52 23 8 1 *"

# Ensure that only one dev workflow runs at a time.
concurrency:
  group: deployment-frontend-dev
  cancel-in-progress: true
  

jobs:
  fe-customers:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.DEPLOY_APP_CUSTOMERS == 'true' }}
    uses: ./.github/workflows/deployment_customers_dev.yml
