name: Deployment Frontend (DEV)
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    # Run once a day. 7PM UTC.
    - cron: "0 19 * * *"

# Ensure that only one dev workflow runs at a time.
concurrency:
  group: deployment-frontend-dev
  cancel-in-progress: true

jobs:
  fe-customers:
    if: ${{ inputs.DEPLOY_APP_CUSTOMERS }}
    uses: ./.github/workflows/deployment_customers_dev.yml
