name: X Deployment Customers (DEV)
on:
  workflow_call:

jobs:
  customers:
    uses: ./.github/workflows/x_lib_deployment_apps_base.yml
    with:
      DEPLOY_IOS_APPS: true
    secrets:
      GCP_CREDENTIALS_BASE64: ${{ secrets.GCP_CREDENTIALS_BASE64_PLACE_DEV }}

